spring.application.name=springboot-ai

server.port=8089

gemini.api.key=${GOOGLE_API_KEY}
gemini.model=gemini-3-flash-preview
gemini.image.model=gemini-2.5-flash-image
#gemini.image.model=gemini-2.0-flash-preview-image-generation

